In [6]:
import numpy as np
from copy import deepcopy

In [7]:
A=np.array([[2,-1,0,0,0],[ -1,2,-1,0,0],[0,-1,2,-1,0],[0,0,-1,2,-1],[0,0,0,-1,2]],dtype=np.float32)

In [8]:
def forward_sweep(A,b):
    A_prime=deepcopy(A)
    b_prime=deepcopy(b)
    A_prime[0]/=A[0,0]
    b_prime[0]/=A[0,0]
    for i in range(1,A.shape[0]):
        b_prime[i]=(b_prime[i]-A_prime[i,i-1]/A_prime[i-1,i-1]*b_prime[i-1])/(A_prime[i,i]-A_prime[i,i-1]/A_prime[i-1,i-1]*A_prime[i-1,i])
        
        A_prime[i]=(A_prime[i]-A_prime[i,i-1]/A_prime[i-1,i-1]*A_prime[i-1])/(A_prime[i,i]-A_prime[i,i-1]/A_prime[i-1,i-1]*A_prime[i-1,i])
    
    return A_prime,b_prime

In [9]:
def solve_tridiagonal(A,b):
    A_prime,b_prime=forward_sweep(A,b)
    x=np.zeros_like(b)
    x[-1]=b_prime[-1]
    for i in reversed(range(b.shape[0]-1)):
        x[i]=b_prime[i]-A_prime[i,i+1]*x[i+1]
    return x

In [10]:
I=np.eye(A.shape[0],dtype=np.float32)
solution=solve_tridiagonal(A,I)
A,I,solution,A@solution

(array([[ 2., -1.,  0.,  0.,  0.],
        [-1.,  2., -1.,  0.,  0.],
        [ 0., -1.,  2., -1.,  0.],
        [ 0.,  0., -1.,  2., -1.],
        [ 0.,  0.,  0., -1.,  2.]], dtype=float32),
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], dtype=float32),
 array([[0.8333334 , 0.66666675, 0.50000006, 0.33333334, 0.16666669],
        [0.66666675, 1.3333335 , 1.0000001 , 0.6666667 , 0.33333337],
        [0.5000001 , 1.0000002 , 1.5000001 , 1.        , 0.50000006],
        [0.33333337, 0.66666675, 1.        , 1.3333333 , 0.6666667 ],
        [0.16666667, 0.33333334, 0.5       , 0.6666666 , 0.8333333 ]],
       dtype=float32),
 array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00],
        [ 0.0000000e+00,  1.0000000e+00,  1.1920929e-07,  0.0000000e+00,
          0.0000000e+00],
        [ 1.1920929e-07,  2.3841858e-07,  1.0000000e+00,  0.0000000e+